my_string = input('Введите любую строку: ')
print('Количество символов в строке: ', len(my_string))
print('Строка в верхнем регистре - ', my_string .upper())
print('Строка в нижнем регистре - ', my_string .lower())
print('Строка без пробелов - ', my_string .replace(' ', ''))
print('Первый символ строки - ', my_string[0])
print('Последний символ строки - ', my_string[-1])
